### ISSUE TITLE
To-Do's for GitHub Repository

### ISSUE THREAD

**Issue by Fontanapink** [ucl-cssb/MIMIC#13]
Things we need to consider for our GitHub Repository:

- [ ] make tags for different release versions

- [ ] make PyTests for this project

- [ ]  make Codecov coverage test

- [ ]  add Licence.md

**Comment by Fontanapink** [comment]
Also

- [ ] Add automatic tags to BUG and FEATURE REQUEST issues
